#!/usr/bin/guile \
-e main -s
!#

;; Entry point, parses stdin, command line and call pretty printer
(use-modules (ice-9 getopt-long))
(use-modules (json))

(use-modules ((logipp latex-pp) #:prefix ltx:))

(define version "0.0")

(define (help progname)
  (format #t "\
Usage: ~a [options]
  -m, --symbols    Specify a guile file containing an association list
  -V, --version    Display version
  -h, --help       Display this help
"
          progname))

(define option-spec
  '((symbols (single-char #\m) (value #t))
    (version (single-char #\V) (value #f))
    (help    (single-char #\h) (value #f))))

(define (main args)
  (let* ((options (getopt-long args option-spec))
         (symbols (option-ref options 'symbols #f))
         (help-wanted (option-ref options 'help #f))
         (version-wanted (option-ref options 'version #f)))
    (if (or help-wanted version-wanted)
        (begin
          (if version-wanted
              (format #t "~a\n" version))
          (if help-wanted
              (help (car args))))
        (if symbols
            (let* ((symport (open-input-file symbols))
                   (symalist (read symport)))
              (if (list? symalist)
                  (ltx:pp (json->scm) symalist)
                  (throw 'wrong-symbols-map)))
            (ltx:pp (json->scm))))))
